using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Movement : MonoBehaviour
{
    private Rigidbody rb; 
    private float movespeed; 
    private float dirX, dirZ;
    

    // Start is called before the first frame update
    void Start()
    {
        movespeed = 3f; 
        rb = GetComponent<Rigidbody>();
    }

    // Update is called once per frame
    void Update()
    {
        dirX = Input.GetAxis("Horizontal") * movespeed; 
        dirZ = Input.GetAxis("Vertical") * movespeed;

    }

    private void FixedUpdate() 
    { 
        rb.velocity = new Vector3(dirX, rb.velocity.y, dirZ); 
    }

}
